"""add weekly campaign workflow

Revision ID: 11c854d63a5b
Revises: 7516fa3f7cf0
Create Date: 2026-06-19 15:32:17.024670
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '11c854d63a5b'
down_revision: str | None = '7516fa3f7cf0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_zones',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_zones_name'), 'delivery_zones', ['name'], unique=False)
    op.create_table('pickup_points',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pickup_points_name'), 'pickup_points', ['name'], unique=False)
    op.create_table('sales_campaigns',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('order_open_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_close_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_campaigns_delivery_date'), 'sales_campaigns', ['delivery_date'], unique=False)
    op.create_index(op.f('ix_sales_campaigns_name'), 'sales_campaigns', ['name'], unique=False)
    op.create_index(op.f('ix_sales_campaigns_status'), 'sales_campaigns', ['status'], unique=False)
    op.create_table('campaign_products',
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('unit_snapshot', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('available_quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('reserved_quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['sales_campaigns.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_products_campaign_id'), 'campaign_products', ['campaign_id'], unique=False)
    op.add_column('order_items', sa.Column('campaign_product_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'order_items', 'campaign_products', ['campaign_product_id'], ['id'])
    op.add_column('orders', sa.Column('campaign_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_orders_campaign_id'), 'orders', ['campaign_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'sales_campaigns', ['campaign_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_campaign_id'), table_name='orders')
    op.drop_column('orders', 'campaign_id')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'campaign_product_id')
    op.drop_index(op.f('ix_campaign_products_campaign_id'), table_name='campaign_products')
    op.drop_table('campaign_products')
    op.drop_index(op.f('ix_sales_campaigns_status'), table_name='sales_campaigns')
    op.drop_index(op.f('ix_sales_campaigns_name'), table_name='sales_campaigns')
    op.drop_index(op.f('ix_sales_campaigns_delivery_date'), table_name='sales_campaigns')
    op.drop_table('sales_campaigns')
    op.drop_index(op.f('ix_pickup_points_name'), table_name='pickup_points')
    op.drop_table('pickup_points')
    op.drop_index(op.f('ix_delivery_zones_name'), table_name='delivery_zones')
    op.drop_table('delivery_zones')
    # ### end Alembic commands ###
