"""add pricing settlement model

Revision ID: 6fb040551fb5
Revises: 90e58f34cbaa
Create Date: 2026-06-20 12:38:25.213948
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '6fb040551fb5'
down_revision: str | None = '90e58f34cbaa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_financial_adjustments',
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('adjustment_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['sales_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_financial_adjustments_adjustment_type'), 'campaign_financial_adjustments', ['adjustment_type'], unique=False)
    op.create_index(op.f('ix_campaign_financial_adjustments_campaign_id'), 'campaign_financial_adjustments', ['campaign_id'], unique=False)
    op.add_column('campaign_products', sa.Column('cost_price_snapshot', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('campaign_products', sa.Column('sale_price_snapshot', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('campaign_products', sa.Column('margin_unit_snapshot', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('delivery_zones', sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('order_items', sa.Column('unit_cost_snapshot', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('order_items', sa.Column('unit_sale_price_snapshot', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('order_items', sa.Column('cost_total_snapshot', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('order_items', sa.Column('sale_total_snapshot', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('order_items', sa.Column('margin_total_snapshot', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('orders', sa.Column('neighborhood', sa.String(length=120), nullable=True))
    op.add_column('orders', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('orders', sa.Column('complement', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('delivery_agent', sa.String(length=120), nullable=True))
    op.add_column('orders', sa.Column('payment_fee_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('orders', sa.Column('net_total_after_fees', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('payment_methods', sa.Column('fee_fixed', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('payment_methods', sa.Column('fee_percent', sa.Numeric(precision=7, scale=4), nullable=True))
    op.add_column('products', sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('products', sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'sale_price')
    op.drop_column('products', 'cost_price')
    op.drop_column('payment_methods', 'fee_percent')
    op.drop_column('payment_methods', 'fee_fixed')
    op.drop_column('orders', 'net_total_after_fees')
    op.drop_column('orders', 'payment_fee_amount')
    op.drop_column('orders', 'delivery_agent')
    op.drop_column('orders', 'complement')
    op.drop_column('orders', 'city')
    op.drop_column('orders', 'neighborhood')
    op.drop_column('order_items', 'margin_total_snapshot')
    op.drop_column('order_items', 'sale_total_snapshot')
    op.drop_column('order_items', 'cost_total_snapshot')
    op.drop_column('order_items', 'unit_sale_price_snapshot')
    op.drop_column('order_items', 'unit_cost_snapshot')
    op.drop_column('delivery_zones', 'estimated_cost')
    op.drop_column('campaign_products', 'margin_unit_snapshot')
    op.drop_column('campaign_products', 'sale_price_snapshot')
    op.drop_column('campaign_products', 'cost_price_snapshot')
    op.drop_index(op.f('ix_campaign_financial_adjustments_campaign_id'), table_name='campaign_financial_adjustments')
    op.drop_index(op.f('ix_campaign_financial_adjustments_adjustment_type'), table_name='campaign_financial_adjustments')
    op.drop_table('campaign_financial_adjustments')
    # ### end Alembic commands ###
