"""add alice operational data model

Revision ID: 90e58f34cbaa
Revises: 11c854d63a5b
Create Date: 2026-06-20 10:36:41.123284
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision: str = '90e58f34cbaa'
down_revision: str | None = '11c854d63a5b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('cpf', sa.String(length=32), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('neighborhood', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_full_name'), 'customers', ['full_name'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_table('payment_methods',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('requires_extra_data', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_methods_code'), 'payment_methods', ['code'], unique=True)
    op.create_table('campaign_rules',
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('order_days', postgresql.ARRAY(sa.String(length=16)), nullable=False),
    sa.Column('order_close_time', sa.Time(), nullable=True),
    sa.Column('minimum_order_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('minimum_order_exceptions', sa.Text(), nullable=True),
    sa.Column('process_by_order_time', sa.Boolean(), nullable=False),
    sa.Column('confirmation_required', sa.Boolean(), nullable=False),
    sa.Column('proof_required', sa.Boolean(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['sales_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_rules_campaign_id'), 'campaign_rules', ['campaign_id'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('basket_type_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('frequency', sa.String(length=32), nullable=False),
    sa.Column('deliveries_per_month', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('average_items', sa.Integer(), nullable=True),
    sa.Column('average_weight_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('serves_people', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['basket_type_id'], ['basket_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_name'), 'subscription_plans', ['name'], unique=False)
    op.create_table('order_payment_details',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('method_code', sa.String(length=64), nullable=False),
    sa.Column('cpf', sa.String(length=32), nullable=True),
    sa.Column('billing_name', sa.String(length=255), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('billing_email', sa.String(length=255), nullable=True),
    sa.Column('billing_phone', sa.String(length=64), nullable=True),
    sa.Column('payment_link', sa.Text(), nullable=True),
    sa.Column('proof_received', sa.Boolean(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_payment_details_order_id'), 'order_payment_details', ['order_id'], unique=False)
    op.create_table('payment_confirmations',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('method_code', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_confirmations_order_id'), 'payment_confirmations', ['order_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('subscription_plan_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('preferred_pickup_point_id', sa.Uuid(), nullable=True),
    sa.Column('delivery_zone_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['delivery_zone_id'], ['delivery_zones.id'], ),
    sa.ForeignKeyConstraint(['preferred_pickup_point_id'], ['pickup_points.id'], ),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('basket_types', sa.Column('average_items', sa.Integer(), nullable=True))
    op.add_column('basket_types', sa.Column('average_weight_kg', sa.Numeric(precision=12, scale=3), nullable=True))
    op.add_column('basket_types', sa.Column('serves_people', sa.String(length=120), nullable=True))
    op.add_column('campaign_products', sa.Column('producer_name_snapshot', sa.String(length=255), nullable=True))
    op.add_column('campaign_products', sa.Column('offer_type', sa.String(length=64), server_default='weekly_offer', nullable=False))
    op.add_column('campaign_products', sa.Column('display_order', sa.Integer(), server_default='0', nullable=False))
    op.add_column('campaign_products', sa.Column('min_quantity', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False))
    op.add_column('campaign_products', sa.Column('max_quantity', sa.Numeric(precision=12, scale=3), nullable=True))
    op.add_column('campaign_products', sa.Column('requires_confirmation', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('delivery_zones', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('delivery_zones', sa.Column('area', sa.String(length=120), nullable=True))
    op.add_column('delivery_zones', sa.Column('restrictions', sa.Text(), nullable=True))
    op.add_column('delivery_zones', sa.Column('is_supported', sa.Boolean(), server_default=sa.true(), nullable=False))
    op.add_column('order_items', sa.Column('offer_type', sa.String(length=64), nullable=True))
    op.add_column('order_items', sa.Column('producer_name_snapshot', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('customer_id', sa.Uuid(), nullable=True))
    op.add_column('orders', sa.Column('pickup_point_id', sa.Uuid(), nullable=True))
    op.add_column('orders', sa.Column('delivery_zone_id', sa.Uuid(), nullable=True))
    op.add_column('orders', sa.Column('payment_method_id', sa.Uuid(), nullable=True))
    op.add_column('orders', sa.Column('source', sa.String(length=64), server_default='web', nullable=False))
    op.add_column('orders', sa.Column('confirmation_status', sa.String(length=32), server_default='pending', nullable=False))
    op.add_column('orders', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('delivery_fee', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'delivery_zones', ['delivery_zone_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'payment_methods', ['payment_method_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'pickup_points', ['pickup_point_id'], ['id'])
    op.add_column('pickup_points', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('pickup_points', sa.Column('neighborhood', sa.String(length=120), nullable=True))
    op.add_column('pickup_points', sa.Column('weekday_availability', sa.String(length=255), nullable=True))
    op.add_column('pickup_points', sa.Column('time_window', sa.String(length=120), nullable=True))
    op.add_column('pickup_points', sa.Column('has_refrigeration', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('pickup_points', sa.Column('is_condo_only', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('products', sa.Column('producer_name_snapshot', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('offer_type', sa.String(length=64), server_default='weekly_offer', nullable=False))
    op.add_column('products', sa.Column('is_refrigerated', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('products', sa.Column('is_frozen', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('products', sa.Column('is_addon', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('products', sa.Column('is_donation', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'category',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('products', 'is_donation')
    op.drop_column('products', 'is_addon')
    op.drop_column('products', 'is_frozen')
    op.drop_column('products', 'is_refrigerated')
    op.drop_column('products', 'offer_type')
    op.drop_column('products', 'producer_name_snapshot')
    op.drop_column('pickup_points', 'is_condo_only')
    op.drop_column('pickup_points', 'has_refrigeration')
    op.drop_column('pickup_points', 'time_window')
    op.drop_column('pickup_points', 'weekday_availability')
    op.drop_column('pickup_points', 'neighborhood')
    op.drop_column('pickup_points', 'city')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_column('orders', 'delivery_fee')
    op.drop_column('orders', 'confirmed_at')
    op.drop_column('orders', 'submitted_at')
    op.drop_column('orders', 'confirmation_status')
    op.drop_column('orders', 'source')
    op.drop_column('orders', 'payment_method_id')
    op.drop_column('orders', 'delivery_zone_id')
    op.drop_column('orders', 'pickup_point_id')
    op.drop_column('orders', 'customer_id')
    op.drop_column('order_items', 'producer_name_snapshot')
    op.drop_column('order_items', 'offer_type')
    op.drop_column('delivery_zones', 'is_supported')
    op.drop_column('delivery_zones', 'restrictions')
    op.drop_column('delivery_zones', 'area')
    op.drop_column('delivery_zones', 'city')
    op.drop_column('campaign_products', 'requires_confirmation')
    op.drop_column('campaign_products', 'max_quantity')
    op.drop_column('campaign_products', 'min_quantity')
    op.drop_column('campaign_products', 'display_order')
    op.drop_column('campaign_products', 'offer_type')
    op.drop_column('campaign_products', 'producer_name_snapshot')
    op.drop_column('basket_types', 'serves_people')
    op.drop_column('basket_types', 'average_weight_kg')
    op.drop_column('basket_types', 'average_items')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_payment_confirmations_order_id'), table_name='payment_confirmations')
    op.drop_table('payment_confirmations')
    op.drop_index(op.f('ix_order_payment_details_order_id'), table_name='order_payment_details')
    op.drop_table('order_payment_details')
    op.drop_index(op.f('ix_subscription_plans_name'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_campaign_rules_campaign_id'), table_name='campaign_rules')
    op.drop_table('campaign_rules')
    op.drop_index(op.f('ix_payment_methods_code'), table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_full_name'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
